# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtf" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "8e785cfc8f613f85a7008ce85d0333f5775866dfd45aec5c15b2d72c91d1083e"
      url "https://github.com/ParthKadam11/WTFisRunning/releases/download/v#{version}/wtf_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0aa42b1213ce8a4bef0be9d4968c81b5316fa1d7f2aea77ac64d942a0a1300d5"
      url "https://github.com/ParthKadam11/WTFisRunning/releases/download/v#{version}/wtf_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "58ceb97c88dd390f458eec75c926eaaca81616bd479113f196d5af739ae7888d"
      url "https://github.com/ParthKadam11/WTFisRunning/releases/download/v#{version}/wtf_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3bb2dd6e1976e9d1f756b11bbe47bd362a7d643d0e4da18886d0053245227729"
      url "https://github.com/ParthKadam11/WTFisRunning/releases/download/v#{version}/wtf_linux_amd64.tar.gz"
    end
  end

  name "wtf"
  desc "See what the fuck is actually running on your Linux server"
  homepage "https://github.com/ParthKadam11/WTFisRunning"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtf"]
    end
  end

  # No zap stanza required
end
